name: firstWorkflow
on: 
  push:
    branches:
        - main
  workflow_dispatch:
jobs:
  test-job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Print "Description"
        run: echo "Hands-On for first GitHub Actions workflow" //command line command
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Conclude the Job
        run: echo "First job executed"
  test-job2:
    needs: test-job1
    runs-on: ubuntu-latest
    steps:
      - name: Print Job Description
        run: echo "A second test job defined"
       
